//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infs3204_prac3.AusPostcodeValidationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AusPostcodeValidationServiceReference.IAusPostcodeValidationService")]
    public interface IAusPostcodeValidationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAusPostcodeValidationService/PostcodeValidation", ReplyAction="http://tempuri.org/IAusPostcodeValidationService/PostcodeValidationResponse")]
        bool PostcodeValidation(int postcode, string state);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAusPostcodeValidationServiceChannel : infs3204_prac3.AusPostcodeValidationServiceReference.IAusPostcodeValidationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AusPostcodeValidationServiceClient : System.ServiceModel.ClientBase<infs3204_prac3.AusPostcodeValidationServiceReference.IAusPostcodeValidationService>, infs3204_prac3.AusPostcodeValidationServiceReference.IAusPostcodeValidationService {
        
        public AusPostcodeValidationServiceClient() {
        }
        
        public AusPostcodeValidationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AusPostcodeValidationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AusPostcodeValidationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AusPostcodeValidationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PostcodeValidation(int postcode, string state) {
            return base.Channel.PostcodeValidation(postcode, state);
        }
    }
}
