//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infs3204_prac2.ColorConverterServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ColorConverterServiceReference.ColorConverterServiceSoap")]
    public interface ColorConverterServiceSoap {
        
        // CODEGEN: Generating message contract since element name color from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ColorToCode", ReplyAction="*")]
        infs3204_prac2.ColorConverterServiceReference.ColorToCodeResponse ColorToCode(infs3204_prac2.ColorConverterServiceReference.ColorToCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ColorToCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ColorToCode", Namespace="http://tempuri.org/", Order=0)]
        public infs3204_prac2.ColorConverterServiceReference.ColorToCodeRequestBody Body;
        
        public ColorToCodeRequest() {
        }
        
        public ColorToCodeRequest(infs3204_prac2.ColorConverterServiceReference.ColorToCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ColorToCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string color;
        
        public ColorToCodeRequestBody() {
        }
        
        public ColorToCodeRequestBody(string color) {
            this.color = color;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ColorToCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ColorToCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public infs3204_prac2.ColorConverterServiceReference.ColorToCodeResponseBody Body;
        
        public ColorToCodeResponse() {
        }
        
        public ColorToCodeResponse(infs3204_prac2.ColorConverterServiceReference.ColorToCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ColorToCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ColorToCodeResult;
        
        public ColorToCodeResponseBody() {
        }
        
        public ColorToCodeResponseBody(string ColorToCodeResult) {
            this.ColorToCodeResult = ColorToCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ColorConverterServiceSoapChannel : infs3204_prac2.ColorConverterServiceReference.ColorConverterServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ColorConverterServiceSoapClient : System.ServiceModel.ClientBase<infs3204_prac2.ColorConverterServiceReference.ColorConverterServiceSoap>, infs3204_prac2.ColorConverterServiceReference.ColorConverterServiceSoap {
        
        public ColorConverterServiceSoapClient() {
        }
        
        public ColorConverterServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ColorConverterServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColorConverterServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColorConverterServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        infs3204_prac2.ColorConverterServiceReference.ColorToCodeResponse infs3204_prac2.ColorConverterServiceReference.ColorConverterServiceSoap.ColorToCode(infs3204_prac2.ColorConverterServiceReference.ColorToCodeRequest request) {
            return base.Channel.ColorToCode(request);
        }
        
        public string ColorToCode(string color) {
            infs3204_prac2.ColorConverterServiceReference.ColorToCodeRequest inValue = new infs3204_prac2.ColorConverterServiceReference.ColorToCodeRequest();
            inValue.Body = new infs3204_prac2.ColorConverterServiceReference.ColorToCodeRequestBody();
            inValue.Body.color = color;
            infs3204_prac2.ColorConverterServiceReference.ColorToCodeResponse retVal = ((infs3204_prac2.ColorConverterServiceReference.ColorConverterServiceSoap)(this)).ColorToCode(inValue);
            return retVal.Body.ColorToCodeResult;
        }
    }
}
