//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infs3204_prac2.ColorMixerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ColorMixerServiceReference.ColorMixerServiceSoap")]
    public interface ColorMixerServiceSoap {
        
        // CODEGEN: Generating message contract since element name code1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MixCodes", ReplyAction="*")]
        infs3204_prac2.ColorMixerServiceReference.MixCodesResponse MixCodes(infs3204_prac2.ColorMixerServiceReference.MixCodesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MixCodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MixCodes", Namespace="http://tempuri.org/", Order=0)]
        public infs3204_prac2.ColorMixerServiceReference.MixCodesRequestBody Body;
        
        public MixCodesRequest() {
        }
        
        public MixCodesRequest(infs3204_prac2.ColorMixerServiceReference.MixCodesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MixCodesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string code1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code2;
        
        public MixCodesRequestBody() {
        }
        
        public MixCodesRequestBody(string code1, string code2) {
            this.code1 = code1;
            this.code2 = code2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MixCodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MixCodesResponse", Namespace="http://tempuri.org/", Order=0)]
        public infs3204_prac2.ColorMixerServiceReference.MixCodesResponseBody Body;
        
        public MixCodesResponse() {
        }
        
        public MixCodesResponse(infs3204_prac2.ColorMixerServiceReference.MixCodesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MixCodesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MixCodesResult;
        
        public MixCodesResponseBody() {
        }
        
        public MixCodesResponseBody(string MixCodesResult) {
            this.MixCodesResult = MixCodesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ColorMixerServiceSoapChannel : infs3204_prac2.ColorMixerServiceReference.ColorMixerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ColorMixerServiceSoapClient : System.ServiceModel.ClientBase<infs3204_prac2.ColorMixerServiceReference.ColorMixerServiceSoap>, infs3204_prac2.ColorMixerServiceReference.ColorMixerServiceSoap {
        
        public ColorMixerServiceSoapClient() {
        }
        
        public ColorMixerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ColorMixerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColorMixerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColorMixerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        infs3204_prac2.ColorMixerServiceReference.MixCodesResponse infs3204_prac2.ColorMixerServiceReference.ColorMixerServiceSoap.MixCodes(infs3204_prac2.ColorMixerServiceReference.MixCodesRequest request) {
            return base.Channel.MixCodes(request);
        }
        
        public string MixCodes(string code1, string code2) {
            infs3204_prac2.ColorMixerServiceReference.MixCodesRequest inValue = new infs3204_prac2.ColorMixerServiceReference.MixCodesRequest();
            inValue.Body = new infs3204_prac2.ColorMixerServiceReference.MixCodesRequestBody();
            inValue.Body.code1 = code1;
            inValue.Body.code2 = code2;
            infs3204_prac2.ColorMixerServiceReference.MixCodesResponse retVal = ((infs3204_prac2.ColorMixerServiceReference.ColorMixerServiceSoap)(this)).MixCodes(inValue);
            return retVal.Body.MixCodesResult;
        }
    }
}
